### ISSUE TITLE
Login credentials from apihub.txt not considered when using aria2c

### ISSUE THREAD

**Issue by slingshot1980** [olivierhagolle/Sentinel-download#23]
Hi Olivier,
When the aria2-argument is provided in the request, e.g.
python  Sentinel_download.py --downloader aria2 -s S1*IW_SLC --lat 39 --lon 68.3 -a apihub.txt 

the resulting call to aria2c does not consider apihub.txt:
aria2c --check-certificate=false --http-user="guest" --http-passwd="guest"  --continue -o query_results.xml "https://scihub.copernicus.eu/apihub/search?q=footprint:\"Intersects(39.000000,68.300000)\" filename:S1*IW_SLC*&rows=100"

The "guest" account does not seem to work any more, I get an authentication error (code 24).

Best wishes,
David

**Comment by olivierhagolle** [comment]
Dear David, 
are you sure you are using the right apihub file ? Because the .py file does not contain "guest", so it has to take it from somewhere, and I guess it was the provided apihub.txt file

Coud you do the test again after checking the apihub in the directory where you start Sentinel_download.py ?
Best regards,
Olivier

**Comment by slingshot1980** [comment]
You are right, I have two configurations on different machines and mixed it up. Sorry for the inconvenience, thanks for the immediate reply.

Best,
David
